language: python

matrix:
    include:
        - python: 3.8

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda install conda-build
    - conda config --add channels conda-forge
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION fenics dolfin-adjoint mshr matplotlib scipy pyyaml memory-profiler pytest
    - conda activate test-environment
    - pip install -e .


script:
    - pytest -v