os:
    - linux
    # - osx

language: python

matrix:
    include:
        - python: 3.8

before_install:
    - if  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - sh install.sh
    # - conda create --yes -n test-environment python=$PYTHON_VERSION
    # - source activate test-environment
    # - conda install --yes -c conda-forge fenics dolfin-adjoint mshr matplotlib scipy pyyaml memory_profiler pytest
    # - pip install -e .
    # - pip install git+https://github.com/blechta/tsfc.git@2018.1.0
    # - pip install git+https://github.com/blechta/COFFEE.git@2018.1.0
    # - pip install git+https://github.com/blechta/FInAT.git@2018.1.0
    # - pip install singledispatch networkx pulp

script:
    - pytest -v