# General options
general:
    name: "2D"
    preappend_datetime: false
    output: ["mesh","initial_guess","turbine_force","solution"]
    output_type: "xdmf"
    dolfin_adjoint: true

# Wind Farm constants for a grid farm
wind_farm:
    imported: false
    HH: 90
    RD: 126
    thickness: 10
    yaw: 0
    axial: 0.33
    ex_x: [-1800,1800]
    ex_y: [-1800,1800]
    grid_rows: 6
    grid_cols: 6

# Domain Constants for a Box Domain
domain:
    #                      # Description           | Units
    x_range: [-2500, 2500]        # x-range of the domain | m
    y_range: [-2500, 2500]        # y-range of the domain | m
    nx: 50                 # Number of x-nodes     | -
    ny: 50                 # Number of y-nodes     | -

problem:
    type: taylor-hood

solver:
    type: taylor-hood

optimization:
    controls: [layout]
    layout_bounds: [[-1600, 1600],[-1600, 1600]]
    taylor_test: False
    optimization: False
    gradient: True
